### ISSUE TITLE
spire access ssh should complain more loudly if ssh-add fails

### ISSUE THREAD

**Issue by ichung** [sipb/homeworld#159] opened 2017-12-17 22:32 UTC
Currently it's easy to miss the error.

**Comment by krawthekrow** [comment] 2017-12-28 20:46
Turns out that this does not actually fix the error I had encountered, since ssh-add exits with return code 0. The problem was that [gnome-keyring masquerades as ssh-agent](https://bugzilla.gnome.org/show_bug.cgi?id=697464) but does not support certificates. Until [this is fixed](https://bugzilla.gnome.org/show_bug.cgi?id=775981), it might be worthwhile to detect this case by searching for "add failed" in the ssh-add output. At the same time, the line "or, perhaps your agent is broken; consider killing it and launching a new one." could be removed since it wouldn't show when this particular problem occurs.

**Comment by celskeggs** [comment] 2017-12-28 22:28
Since you have the ability to reproduce this bug, and I don't, can you take care of resolving this correctly?

**Closed** 2018-01-08 16:35 UTC
Labels: category current-known-bugs, micro
